### PR TITLE
Fix a few issues with transitions.

### PR DESCRIPTION
**Pull request by manthey**
There were several bugs with momentum, transitions, and spring-back.

If momentum was occurring, a mouse wheel event would take place in the wrong location.  For instance, pan a map such that it has momentum and use the mouse wheel to zoom.  The map zooms, but is pans back suddenly to the start of the momentum location.  Now, when a new mouse action occurs, momentum is canceled.

If a transition was occurring, it would "fight" with mouse interaction.  Now, when a mouse action occurs, a transition is canceled and the transitioncancel event is triggered.

Springback used hard-coded boundaries in a fixed coordinate system.  Now it uses maxBounds in the map coordinate system.

Added a spring to bounds option to the tiles example.

Moved the mockAnimationFrame functions to the testUtils.js file so it can be used in multiple tests.

Added a mockDate routine to facilitate testing momentum and springback.

This fixes issue #537.

### CODE REVIEW

**Comment by brianhelba** [comment]
@manthey Can we demo this to @law12019 ? I'd be interested to get his feedback on the behavior.

**Comment by jbeezley** [comment]
Yeah, that momentum/spring code really should go somewhere else.  I think it could be handled pretty easily using `map.transition` rather than producing a completely independent code path.  Perhaps a topic for a future refactor.

In any case, this change LGTM.

**Comment by aashish24** [comment]
> Yeah, that momentum/spring code really should go somewhere else.

+1

**Comment by aashish24** [comment]
@manthey  LGTM :+1:

**Pull request merged**
