### PR TITLE
Include git SHA in the built bundle

### LINKED ISSUE #552: Store git hash as part of the internal version.

### PR DESCRIPTION
**Pull request by jbeezley**
Fixes #552

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley looks good to me. IS CI failing because of some system issue?

**Comment by jbeezley** [comment]
The new test is failing when run from CTest.  I'll have to look into it more to find out why.

**Comment by jbeezley** [comment]
PTAL.  The failure was because `execSync` wasn't added until node 0.12.  I added a warning and updated the dashboard machine.

**Comment by manthey** [comment]
LGTM

**Pull request merged**
