### PR TITLE
Fixing position bugs update

### PR DESCRIPTION
**Pull request by aashish24**
Branch with cleaned up history.

### CODE REVIEW

**Comment by aashish24** [comment]
Ref: #422

**Comment by jbeezley** [comment]
I think I fixed the issue with the two renderers test.  It is terribly hacky because the camera doesn't have a "real" initialization method.  That whole code path is being updated in my branch so I didn't attempt to make the fix pretty.

**Comment by jbeezley** [comment]
All tests passing now.  I'm good with this if others are.

**Comment by manthey** [comment]
Looks good from here.

**Comment by aashish24** [comment]
does resize not trigger when in testing? Otherwise looks good to me +1

**Comment by jbeezley** [comment]
It does, but it needs to be done several times because various steps of the resize are skipped before the base layer is added.

**Comment by aashish24** [comment]
Thanks. Seems like we need to improve this logic a bit. I will have a look at it.

**Comment by jbeezley** [comment]
I wouldn't do any coding on it, I'm touching all the code related to cameras and coordinate conversions in my branch.  I'm cleaning up issues like this as I go.

**Comment by aashish24** [comment]
Sounds good.

**Pull request merged**
