### PR TITLE
fix: Add semantic release.

### PR DESCRIPTION
**Pull request by manthey**
This will make it so we can automatically release features as they are merged to master.

### CODE REVIEW

**Comment by manthey** [comment]
@aashish24 This switches to semantic release.  Henceforth, we can prefix PRs with special tokens (e.g., `feat: new feature`), and when they get merged in, a release will automatically be made.  If you commit to the `beta` branch (or merge to it), a beta release is made.

**Comment by aashish24** [comment]
awesome, I guess the manual change log will be bit behind. Do we need that anymore since now we have the semantic release (which I believe creates a change log)?

**Comment by manthey** [comment]
We'll see how what semantic-release does with the change log.  There will probably be a future PR to harmonize change logs.  For now, I expect we'll manually update CHANGELOG.md until we figure out how to automate it to our satisfaction.

**Review by aashish24 — APPROVED** [review]

**Comment by aashish24** [comment]
> We'll see how what semantic-release does with the change log. There will probably be a future PR to harmonize change logs. For now, I expect we'll manually update CHANGELOG.md until we figure out how to automate it to our satisfaction.

Okay thanks

**Pull request merged**
