### PR TITLE
Add a track feature.

### PR DESCRIPTION
**Pull request by manthey**
The track feature is a set of lines each of which is composed of points with position and strictly monotonically increasing time.  There are utility functions for setting a start and end time.  Two points are interpolated along the track line: one each for the start and end times.  A marker or text value can be rendered at the end time.

Internally, the track is rendered as three line features; one for all the points before the start time, one for the start to the end time, and one for the end time onward.  Additional a marker and/or text feature is used to render the track heads.

This still needs a tutorial or example.

### CODE REVIEW

**Comment by manthey** [comment]
Here is a [rough sample](https://opengeoscience.github.io/geojs/tutorials/editor3/?src=jVBBTsNADLznFdu9Z53SBBG0yQWQuMGBC0c3dtst2d0oMWn7e5JGILghWRp5NDO2xq4eXx7e3l-f1EF8Wyf2Gxiptp4FVUDPld5z4B4l9lo1MQgHqfQzn6PamNJkuk6Usqs0nWFoeteJkks3-YTPAkcccWG1Gvqm0sbANNtP1wrsORrvgjkOurawyOa4NK3.mXYQ6YZ7AEJB8-HkhD2bJnrAzsG4hp1rGQrCvMzXN7QpiruMb6kpM6R8CxRPoY1Iv69buBaQ2G2ky.UNcqNyVGmP3Syc1j-0C7v4w1tYbFPK3OYX&src3=rVVRb9MwEH7vrzjBQ1IpytqUIJFpTyAkEBISIHiY-uAl1y6aG0e20610.e.c2V6XLSkgRNUmzd13330-3zlboWEjWriANaqU.sX7CUCjKizgxUt6fpHQc4mNRV3A.q6ALE9gR7fZgT0.ldoUkE8O0.PJ2RmUGoVFECDFDjXYa2HBdG2rtDVQaXFbN2uwWpQ3sCJkp9FMtiTBwy9YSuo5PrEljgIqSmD.EFDAZeQooiVndfHu-Z2wgjguSRb.wMudOblzutkCvGjoLyR48gM5lkkvcnEycpF5TxYie57AmTvPfHaKNAukCRir1Q2-VVJRfaMr2fFavfFHXdlrJhumzk6mzv6UejGyHh-6GCH16RZH0uQE3XxYv2x8qWFV2ZOtyPrQ.Bm0Lyh71UfOB6x96Osn0HwAPSF4MS6Yc8m6wY-qbnincIsyGrbTSBGz00V8SJn3izhZUlf7IbnwkxFm4r2fgDi0.5TAaUVNHx.bn000hiulSfxOokmgM0hziLAV1FtgWizrVY0VXO2cmZcEtcUN1Ctoabxo1JnXhcd7cFJLqQxWBayENOjVP5Zi1TWlrVUD8Ra1xbsE.P1DU.EDc.urM0xh7-IBNNJimgBOH.jg.t6BL2fLo-3cRYSyPRmYf83NR5VqjJKYSrX-u-DzUd09OX3pz8w02LxjIwsJ3fV.itijHIo5mrMgg64H10MboW9Qf.U77rXtNldKFuGlwN7Qe6n3mFRorW6THvg79xedzfME-HvGLa07XHqMFlXdGW54l9W9LPh94HownOy-51M2x3ywE4T6gQFhr5jRd-1KSan4ZVIwynZW6VrI1BPYeoNfRLPG2Od55sam-kaIeJ5Nj7mGKGOFtg735newVhjrCxf5Kn9uRVnbHR3is8e4x88v).

**Comment by manthey** [comment]
This now has tests and a tutorial.

**Comment by aashish24** [comment]
@manthey this is great. In the sample, the arrow head does not scale. Is it possible to scale it with zoom in and out? Or perhaps the intension is to keep it fixed size?

**Comment by manthey** [comment]
You can scale the markers with zoom by changing the style.  For instance:
```
track.markerStyle({
  radius: 1,
  strokeWidth: 0.1, 
  scaleWithZoom: geo.markerFeature.scaleMode.all
}).draw();
```

**Comment by aashish24** [comment]
@manthey changelog is conflicting fyi

**Pull request merged**
