### PR TITLE
Fixing position bugs

### PR DESCRIPTION
**Pull request by manthey**
This fixes the layer offset bug.

@aashish24, since you are away for a while, I cleaned up your code and added a test.  Also, this expects the parallel projection code to be merged in.  

@jbeezley This should pass once we fix the parallel projection selenium tests since it includes that branch.

### CODE REVIEW

**Comment by manthey** [comment]
@jbeezley Do you know why this failed in the buildbot tests?

**Comment by jbeezley** [comment]
I only looked at it briefly so far.  There are some changes here that could cause the map to display differently than before, but I'm pretty sure there is a bug in here somewhere as well.

**Comment by jbeezley** [comment]
I fixed most of the issues with a one line change.  What is left is a problem with glTwoRenderers that I need to look into still.  The rest just need updated baselines.

**Comment by aashish24** [comment]
@manthey no problem. Thanks, I was going to look at this later this week but appreciate your help here. 

@jbeezley let me know if you still have issues with two renderers. I am planning to do some work later this week. 

- aashish

**Comment by aashish24** [comment]
@manthey let me rewrite my commit messages unless someone else has done it.

**Comment by manthey** [comment]
@aashish24 Rewrite as you see necessary.

**Comment by aashish24** [comment]
Done. Please see #426

**Pull request closed without merging**
