### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley its ready for review

**Comment by jbeezley** [comment]
:+1:

**Comment by ronichoudhury** [comment]
Why is the typeface in this logo different from the one [here](http://www.tangelohub.org/)?  I think for branding purposes we should consider the uniform logo-typeface combo for the TangeloHub line of platforms.

**Comment by jbeezley** [comment]
I wouldn't mind another pass over the logo style.  To me, the color are a bit light.  I think I like [this version](http://opengeoscience.github.io/geojs/images/logo.pdf) better.  Also, I attempted to generate some [favicons](https://github.com/OpenGeoscience/geojs/tree/gh-pages/favicons) from the symbol.  They look okay, but it would be better to generate some with transparent backgrounds.

**Comment by aashish24** [comment]
I was planning to talk to steve about another pass on the logo but didn't want to wait as he is busy at the momement. I will ask him to generate some options.

**Comment by jbeezley** [comment]
@ronichoudhury and I just had a conversation about updating the logo to be more consistent with the other tangelohub logos.  In particular, we should use the same font and limit it to a single base color with multiple shades.  When Steve has time, we should get together and go over what we want.

**Comment by aashish24** [comment]
yup that was the idea Steve and I had. The logo on the tangelohub is close but not perfect. I will send few options to the mailing list for the voting

**Pull request merged**
