### PR TITLE
Remove outdated and broken examples

### PR DESCRIPTION
**Pull request by jbeezley**

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley are we going to replace them with updated / newer examples?

**Comment by jbeezley** [comment]
For the most part, these have been superseded by new examples or tests already.  The only exception is the feature demo, which was written using the old feature api, so would have to be totally rewritten anyway.  I could redo this one, but I don't have time in the near future to do it.

**Comment by aashish24** [comment]
Sounds good. I created an issue for that (https://github.com/OpenGeoscience/geojs/issues/409). Other than that :+1: LGTM

**Comment by aashish24** [comment]
I am wondering why garant is not running?

**Comment by jbeezley** [comment]
http://my.cdash.org/index.php?project=geojs

looks like it is to me.

On Wed, Jul 1, 2015 at 10:01 AM, Aashish Chaudhary <notifications@github.com

**Comment by aashish24** [comment]
Now i see it, thanks.

**Comment by aashish24** [comment]
:+1:

**Pull request merged**
