### PR TITLE
Multipolygon rendering

### PR DESCRIPTION
**Pull request by danlamanna**
@jbeezley Let me know if I did the testing correctly, everything seems to pass for me when I run the tests on garant (image is on midas).

### CODE REVIEW

**Comment by jbeezley** [comment]
Looks great!  Thanks.
[LGTM](http://lgtm.in/i/oMkinunEn)

**Comment by demarle** [comment]
That is the second coolest reviewer comment I've ever seen.

**Comment by aashish24** [comment]
:clap:

**Comment by jbeezley** [comment]
>
> That is the second coolest reviewer comment I've ever seen.
>

Now I'm wondering what the coolest comment is...

**Comment by aashish24** [comment]
Me too :smile_cat:

**Comment by demarle** [comment]
:)

Technically #1 was a commit message, not a reviewer comment.
In VTK do: "git log --author=tshead b9ced31e -n 10 --reverse"

**Comment by jbeezley** [comment]
Oh wow.  The real question is, was Johnson ever found?

**Pull request merged**
