### PR TITLE
WIP: 545 implement grid feature

### PR DESCRIPTION
**Pull request by dcjohnston**
I will take care of all of the following tasks within the week, but the feature is in a place where it can be examined for gross flaws, and the data model I devised can be critiqued. 
- [ ] Testing.
- [ ] Better performance with canvas renderer. 
- [ ] Ensure documentation is consistent with convention and revisions. 
- [ ] Better example, & thumbnail to showcase.

For the grid, the data that is passed in is an array of intensities for each cell in row major order. The grid is constructed with an `upperLeft` property that specifies the position of the first cell in GCS, as well as a `cellSize property`, also in GCS, that specifies the length of each cell (for now they are assumed to be square). It also accepts a `rowCount` property, from which the column count is deduced and used to iterate through the data array.

### CODE REVIEW

**Comment by aashish24** [comment]
yay! Thanks for pushing it @dcjohnston. We will provide some feedback soon.

**Comment by aashish24** [comment]
@dcjohnston we will also need a gl version of this too, will talk to @mbertrand too

**Comment by aashish24** [comment]
@dcjohnston any updates?

**Comment by aashish24** [comment]
@mbertrand  @dcjohnston look like a good progress :clap: I will checkout the code and play with it. One question would is that in the wigglemaps example, we were loading a dataset. I am wondering if you can add a example using that dataset in geojs.

**Comment by mbertrand** [comment]
@aashish24 adding that example dataset is doable, may not get to it this week though.

**Comment by aashish24** [comment]
@dcjohnston are you going to update the example?

**Comment by mbertrandtest** [comment]
@aashish24 I think @dcjohnston needs documentation on the file format of the example from wigglemaps.

**Comment by dcjohnston** [comment]
I found the ascii version in wigglemaps this morning, I need to add the data N/A functionality and that example should work with a little reformatting.

**Comment by aashish24** [comment]
@mbertrand do we have a person assigned for this task?

**Comment by mbertrand** [comment]
@aashish not yet, does it just need to be brought up-to-date with the master branch?  Not sure if there was anything more that Derek didn't get to.

**Comment by mbertrand** [comment]
@aashish24 I brought this branch up to date with master but am not able to push the changes.  Could you check my permissions for this repo? Thanks.

**Comment by jbeezley** [comment]
@mbertrand I added you to the developer group.

**Comment by mbertrand** [comment]
@aashish24 I added more tests and now all checks have passed.

**Comment by aashish24** [comment]
@manthey should we close this?

**Comment by manthey** [comment]
We should refactor it to use the generalized grid class and either update it or replace it.

**Comment by aashish24** [comment]
Sounds good, I would think lets close this for now and when we have time and need, we could refactor it then. what do you think?

**Comment by manthey** [comment]
Closing.  See issue #545 for how this could be revived or the feature could be implemented with modern classes.

**Pull request closed without merging**
