### PR TITLE
Remove remaining references to vgl submodule

### PR DESCRIPTION
**Pull request by jbeezley**

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley does vgl.js will be minified (or not) based on how we are building geojs (its been a while I tried to debug).

**Comment by aashish24** [comment]
Had a related question but other than that :+1:

**Comment by jbeezley** [comment]
It's minified in the minified library, but just concatenated in the other.

**Comment by aashish24** [comment]
Great..thanks!

**Pull request merged**
