### PR TITLE
[WIP] Enable multiple gl layer

### PR DESCRIPTION
**Pull request by aashish24**
Work on this branch is not done yet. Just putting it out here for discussions.

### CODE REVIEW

**Comment by jbeezley** [comment]
Yay!  Looks like some minor issues in the tests.  I'll take a closer look later today.

**Comment by aashish24** [comment]
thanks @jbeezley. This branch make GL layers just like any other layer and now follow the same rules. We should be able to provide multiple views (side by side) etc. Also, I am hoping that with this, it will easy to get the parallel projection working as well.

**Comment by jbeezley** [comment]
Yay!  #154 :boom:
screen shot 2015-06-25 at 9 04 50 pm

**Comment by jbeezley** [comment]
I'll update the baselines tomorrow to account for the tiny shift in the secondary GL layers, but other than that this looks good to me.

**Comment by aashish24** [comment]
Great! @jbeezley we should probably add a test (I liked your demo above!!!). May be you can add that as a test as well?

**Comment by jbeezley** [comment]
I already had a multiple maps test that was disabled.  I have now enabled it, and I uploaded the new baselines.  This PR LGTM:

[LGTM](http://lgtm.in/i/mP6YG5pMn)

**Comment by aashish24** [comment]
:+1: thanks. :clap: merging now.

**Pull request merged**
