### PR TITLE
feat: Add a grid feature

### LINKED ISSUE #545: Implement Grid Feature
Use examples from wigglemaps.

### PR DESCRIPTION
**Pull request by manthey**
This refactors the contourFeature to avoid code duplication, as the grid and contour features are nearly the same.  Specifically, the contour feature has data values at each vertex of a mesh and the grid feature has data values on the elements of the mesh.  The grid feature has solid colors for each mesh element, while the contour feature has interpolated values between the vertices.

This adds a small tutorial.

This closes #545.

### CODE REVIEW

**Comment by aashish24** [comment]
@manthey build issues - holding review until it passes

**Comment by manthey** [comment]
It passes locally (and in a docker build environment).  I'm not sure what is failing in travis.  This is built on top of PR #1079, so if that gets merged, I'll rebase and see if kicking off travis again fixes it.

**Comment by aashish24** [comment]
@manthey I have started the review process on this PR

**Comment by manthey** [comment]
I rebased this to use the github actions.

**Review by aashish24 — APPROVED** [review]
Earlier approved these changes and recently we updated it to use current master

**Pull request merged**
