### PR TITLE
Version 0.9.1

### PR DESCRIPTION
**Pull request by jbeezley**

### CODE REVIEW

**Comment by jbeezley** [comment]
This is ready to go.  I updated the documentation and exposed jquery via the more common variable `jQuery` (where bootstrap looks for it) to fix the examples.

**Comment by manthey** [comment]
LGTM.

Should we load the minified geo.min.js rather than geo.js in the examples, as, since it is webpacked, the source isn't all that readable anyway?

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by aashish24** [comment]
I prefer geo.js as it is easy to debug when I use example for testing something. I heard the same from others too but I am open either way.

**Comment by jbeezley** [comment]
That's only for the main page to load jquery for bootstrap.  The other pages use the non-minified bundle.

**Pull request merged**
