### PR TITLE
[WIP] New gh-pages website

### PR DESCRIPTION
**Pull request by matthewma7**
This is a new gh-pages website.
Live demo can be found https://matthewma7.github.io/geojs/

This is paired with the changes on this branch https://github.com/OpenGeoscience/geojs/tree/website_examples

I started with as gh-pages supported Jekyll project but later found out the existing custom site generating with pug/jade. The previous building is still needed, but it is used for building individual example pages only. So, the ph-pages site building involves two different technology at this moment.
(All old example url should still work)

To build or the develop the website, follow the steps in the [readme](https://github.com/OpenGeoscience/geojs/blob/website/README.md) file.

**There are tasks needs to be completed before merging this PR.** (publish the website)
Below are the items I can think of. More items are welcomed.  Once related information is gathered, I can make the changes or changes can be committed directly to this branch. 
- Fill all text placeholder
  - The highlight section of the welcome page
  - The description in "get started" section
  - Example and tutorial page description
- Review all text content
- Determine the order of examples
  There is a requirement that we want to order the examples not just alphabetically, now the order is controlled by the https://github.com/OpenGeoscience/geojs/blob/website/_data/examples.yml file, it also controls what shows on the examples page.
- Review the download page 
   https://matthewma7.github.io/geojs/download
   I put together an initial download page, but because my unfamiliarity with GeoJS, the content of the page needs to be reviewed. Especially, the part about geo.js and geo.ext.js.
-  The two WMS examples need to be updated. It seems there is a CORS issue with the WMS server.
-  Potentially update the jsdocs template to follow the new website design
-  We want to have some tutorials, the website has a placeholder for them, but the tutorials are pending implementation.

### CODE REVIEW

**Comment by matthewma7** [comment]
@aashish24 @manthey This PR is the website itself.
I put in the changes we talked about earlier. I didn't get the landing page logo transition animation working right, so the implement is a basic transition effect. 
@aashish24, You could add content to this branch directly. I have invited you both as collaborate of my repo https://github.com/matthewma7/geojs, so you should be able to push to its master branch to view changes.

**Comment by aashish24** [comment]
okay thanks @matthewma7

**Comment by matthewma7** [comment]
Initial set of tutorial added

**Comment by jeffbaumes** [comment]
In the title bar, the Hub, in GitHub should be capitalized.

**Pull request closed without merging**
