### PR TITLE
Add controls to the tiles example.

### PR DESCRIPTION
**Pull request by manthey**
Fix an issue in destroying the vgl renderer.

Allow updating the subdomains for a tile layer without having to rebuild the tile layer.

Add support for changing map clamping parameters after initialization.

This partially addresses issue #409.

### CODE REVIEW

**Comment by aashish24** [comment]
This is cool! @manthey. Let me checkout this branch and will review the code.

**Comment by manthey** [comment]
@aashish24 Can you review this branch?

I can add some tests for some of the added functions after PR #485 gets merged in, as I've increased code coverage there and don't want to duplicate that work.  Alternately, I can add tests in a separate PR, if you like this one as it is.

**Comment by aashish24** [comment]
Sorry for the delay, was focused on something else to work and now that's done, I will review it asap

**Comment by aashish24** [comment]
@manthey code changes looks reasonable and the example is great :tada: but I ran into few UI related issues. 

- [ ]  I only see VGL renderer option even though I was hoping to see d3 and html based on the code
- [ ] When I changed the tile-url once, I could not change it second time
- [ ] wrap-y works but when toggled on, it somehow over-ride the clamp-y (this was something I could not reproduce consistently

I am on ubuntu 14.04 chrome

**Comment by manthey** [comment]
Is the Renderer control showing D3 and HTML as options?  If not, what does the DOM show?  If so, is it just not switching to them?  More information, please.

The tile-url control is a HTML5 data list, which is still a relatively new item for browsers.  It is a "combo box" (an editable select control).  You should always be able to edit the text.  The drop-down seems to only work in Chrome if you defocus and refocus the control.  This is probably a browser issue.

Regarding the wrap versus clamp: there are some curious interactions between clamping zoom, requiring discrete zoom, and clamping the directions.  As far as I can tell, these are all correct.  I can't imagine how changing wrapping would affect clamping.  If you can get it into such a state, it would be worth investigating.

Can you share your desktop via VNC or RDP when you are having one of these issues?  If so, I can debug remotely.

**Comment by aashish24** [comment]
> Is the Renderer control showing D3 and HTML as options? If not, what does the DOM show? If so, is it just not switching to them? More information, please.

Just the VGL, the dropdown shows up but no text (blanks). 

> The tile-url control is a HTML5 data list, which is still a relatively new item for browsers. It is a "combo box" (an editable select control). You should always be able to edit the text. The drop-down seems to only work in Chrome if you defocus and refocus the control. This is probably a browser issue.

Probably

> Can you share your desktop via VNC or RDP when you are having one of these issues? If so, I can debug remotely.

Sure, let me know a time this afternoon and we do debug it.

**Comment by aashish24** [comment]
@manthey are you going to update this?

**Comment by manthey** [comment]
All I am waiting for is to know if when you upgraded Chrome it fixed your issue or if I need to look at that further.

**Comment by aashish24** [comment]
> All I am waiting for is to know if when you upgraded Chrome it fixed your issue or if I need to look at that further.

Ah, okay, sorry it wasn't clear will update and let you know.

**Comment by aashish24** [comment]
@manthey I updated to newer chrome and it solved the problem for me :tada: I ran into one installation issue but that was a system specific issue with chrome installation. 

LGTM :+1:

**Pull request merged**
