### PR TITLE
Fix selection rectangle and add selection-based zoom

### PR DESCRIPTION
**Pull request by manthey**
Fix the selection rectangle on rotated maps.  Use the Quad feature instead of the Plane feature.

Add "rubberband" zoom in and zoom out.  By default, this zoom in is performed with shift-left-mouse button, and zoom out with shift-right-mouse-button.

This resolves issues #548 and #346.

This depends on PR #581.

### CODE REVIEW

**Comment by manthey** [comment]
There is an issue when the selection rectangle straddles 180 degrees E or W.

**Comment by aashish24** [comment]
@manthey I will review this one next as I believe the bug has been fixed?.

**Comment by manthey** [comment]
@aashish24 Yes.  Selection and zoom across wrapped maps is now fine.

**Comment by aashish24** [comment]
LGTM :+1: thanks.

**Pull request merged**
