### PR TITLE
Removed deprecated/unused files

### PR DESCRIPTION
**Pull request by aashish24**
As per the release 1.0 plan, removed unused / deprecated code.

### CODE REVIEW

**Comment by aashish24** [comment]
Coverage is :up:

**Comment by manthey** [comment]
I think you meant to remove `src/gl/geomFeature.js`, too.

**Comment by aashish24** [comment]
> I think you meant to remove src/gl/geomFeature.js, too.

Yes, I missed that out in my commit. Should be fixed now.

**Comment by aashish24** [comment]
@jbeezley should I generate new geo.js? Or do we that at the point of release?

**Comment by manthey** [comment]
That gets done at release.

**Comment by aashish24** [comment]
> thanks, that's what I thought so.

**Pull request merged**
