### PR TITLE
Update vtk.js pointFeature

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by manthey** [comment]
@jourdain This doesn't work as written, and I suspect that we are doing things in a more obtuse way than we should.  For ease of trying this out, I've made two interactive tutorial links to allow adjusting the code.  This [link is the existing vtk.js pointFeature](https://opengeoscience.github.io/geojs/tutorials/editor/?src=rVhtcxu3Ef7OX7FxpuFRoU9HHimSUtTUlce1ZuJYYzvNtB6NB7oDScTHAweHk0TJ.O.dxcu9kLScdvqFxMuDxWL32cUebpmCFVvDOSy4DLEVPHYAcpnyU3j2Pfaf9bGf8FxzdQqPcH8Kz2eT8GTSh80pxINwGsGWIA9Srk5h1Nn2zjq4LEwUZ5r.wjZcBV1ZrLo43rnF3RKhBS9ww4-46jGTOUqcjMIoGs9Gg7gPGdMoJwong-FkGuM-OVuRMr.yO.iXVJ-f9WEt1yXCBK2djqIxwowOTtpgMA2Ho.hkOpo5cTHKHw-H8WhYiftFFvAiX.CMFzsS4-l0FEctiVM88XA2mU2HXj88-GQ6GMQnlcCLpUjYQu4IG04GCBw2hc3GYXwym0bDqRM2nIWTk2g0PKkP-1qWhZb5rrDBbDwbjJrCJuNwcIJHG4z9UWfhbDxEk8wqYVdLkbGUZ-ulYDsSB-NxjOvb1huG0WQUxRPvjDgORyO08WTQECl5Lu73pA3i-GSy7Vyjr42zRb7kSmhHL9c7M1OKL0SBrHqFPCkVd5CdUQtdS5HrNq45hJsdHx114AguDOmAQY5kEXmhWZ5wkHO41Z..KFqLQsTTkr8lGSsK02KZYIWRvg83AH6veZ4WewqYyTVTbAWPu3NhsebJFphaGJTiOJgXFre.zRZBx-bMZu7TzsnnZZ6QqSFAeT2gUO2WBYdCK5Ho7hn2xRyC7wK9FEVlAH.-lrSeXQ5gNTIW20eZfUgsKkZnQB3o98sXeNzScOukCcsys3Mf7DIE0FG0Ynkxl2rlfFf1zxxA3vzBE08S2.FTqFKLGQpzBzbzlCuuCmdB89tY8SLRUuEybIbvDFbki.BCoo5-toF-w9Zr.nX4P7LNehm.tKjGsis6-nuu3cILuVrJPHzJNHuD2TMLG5DGqvdrDAH-XpYq4W7lK5FpOosdNKdpoowZrVFqC1vjGtaDIZ8St8h80zt2u60-GRacg3GJ8TXgIKPj192107EeKcy2vl98ErkJYJISmk49xe8bU9Spp8p1SqHoJ223rbWL1rVY80zkFJFOe7vE3iBXbrbFfs.dWn1rS2.wENl86dgfGP7WB7PIpoWfQocF1x-WXLN3vJBZSdsHcXQAhEn2EOTW3q8VwSyNDu5oZ1DUZb4uNREpaLgHosO4C5nn3JglqNRZcP221Dh5JZUOen0YVAqzOjRMHBw-u0HRFlbdwO65M427XCmJ43oT9Aj8YnUjsFAI.G7GjT5WEZJIrCLu9bt6hKWp0SJwMm2qabPkEhknMDU.7BHEEXOfFpazNlpsFPiMZPX.tmJ4Glu6tM6yQ8ngkLp.L0WWGjjMq5umpfaNQRzS29yYfRAxXavFP1nmw4kqsvyBK.nvxki5utIU3u48KRGmF2Y8X-hlDUNBwuxyblL8C6XYJnBrjyDu1UgSsCuuJecVKlwDvOAmSLG0DSr0JjN8DLo4J8qi20AnMpPqq.i5yLILQjSXyDXD-nHz5KK3FtO1OZJcA5ca0B8rzOjA53OREE1BS0gl1gr19YRWYlBg8s-whiBD4YE05gl0HMtx1qlxBNiz83i1mkYBGFXNUZuwi9A6HgDlQyBQZxHjT3QGAn5yLqT2j-cwIMdTI.Z0AMcCXOCsH5BXPoprhDpe1g7-KOJri8Ql4f2BafgRBg3I5jBk2IA80E0feZznIFHJN3F-d7mHHx.Dh7cv357CXNyjBbl3HlAyNHktbF9K-xnFuTJouL1pAmeDbWeH6JVH61LjQkqVihyjtwiqXQ17FklBKdL1MhP1PfMl1HNzO2bqo4dqar2XK15vSCRLxXxjzvvwPKl2DQEu53BHpRpTmqdwJ.QSMEEB2REeOo5Z9QrMWanMu7ohcYVSPlBmSWSJKeSGQ4LEXKA0rPpw3gtpbgwF2s7UwKTSIoOkxHUoo8D0iCsxs6PJlUBotqnoaqrIysk..NAyFnx3fv6EvWr6.m-kP0jIioRb5.JOi2KGTmgXDEFMopu-TcA551itY5zjiRWfG5KZ.pLd0ldCigWlwCTsZRV4yTTYCfD7kmkolt7a6A9uHUe2xGJUfuYmRfVd53eR-tyL4lieunHH458BXstcKrOcUtWxncbIoOOaJJLKpFyZ9ER733EvzHJhicu1p8Jr3AAzlaEa-uk5RcZzoVecCJKnxoRhdbFg.kU7ugxtoyi6prKiD0lGJUGVjpuT1uy09ugrPi.xqi2uuLoS99xftzsQehsIetX162saE-.GcTbaTcnTjrLdKuuduUQC1OdbxYjxS4AnC5U5YLiwfzftKsBcxh.EipOyFGiCpwfv9d9MAbt7l1dV7qEixE42yxCfNyi8Gves2x.P8MY24a.nhxRsAL58qaLFAe1u-8ifqtitxupYc1O2JvH13xZ4hh-VHkPkebo2-G8vfvg6GX2Y.z8Z9w0KuVxyyIxPMuIlp-jd7FLCfRMd-lj5dt2p-Ere8v2a2H9sNRXxvqNa1467T3kaPusQyD24BPsf9v3WpzvxEnPMr.KuepYBoTs7jzFB18jp9qFrFmPjwLsCPf2gLGKN8QlxYvc90FXGVKL9KVwfHr3ZTsFpsfUPivPqecTIcRIqna2qPTSP5a19fzT9qoStnUVpeudlxMfB.Sm9XW7CDJOTG9r4IWbvEPMmsjWyTQAEjz59IuVOG5xIqXyBR78F3oUwObMPqQCNIvaJNXixHsOkB3-BKJyMUUAUDsctGSYFPiHhY.cmY8nnbr-reIq.UlExgY0NzzJ5h42F4jzH.5uspHGBl8pCYuNWyIzr7jXWYWfmRrZnThW7IyYeH3XuECvvzNczhpIsddAOCHK1CdIx4q1LwnVZLAP.ChlF.vVx.CdfHXsd.8HV9HOl1LYP4yiiDHN0.B8_).  This [link is this branch (adjusted to work in the tutorial context)](https://opengeoscience.github.io/geojs/tutorials/editor/?src=rVltUxs5Ev7uX9Gbq1sPrDN-GRtjWHaPQNhQFQIVyO7tpVKUmJFtbcYj14wMGOL.fq2WNKMxDsldbT6QkdTverrVkm9ZDjM2hwOYcBniV.DYAMhkwvfgxT9w.KKF45hniud78Aj3e.ByNAx3hi1Y7kHUDXc7sNIkD1LO9qDfWG3tN5AtjHPOFH.LljwPmrKYNXG-cYvaYqEEL1DhR-R6TGWGEof9sNMZjPrdqAUpUyinEw67veFuhHoyNtPGvON38KfMP79owVzOF0gmNO9uvzNAMrLBSut2d8NeP9rZ7Y-suAjlD3q9qN8rxb2VBRxmE57yYk1itLvbjzo1ibvocW80HO32nH3o-HC32412SoFHUxGziVwT1ht2kbDnCxsNwmhntNvp7VphvVE43On0ezuVs2.kolAyWxfWHQ1G3b4vbDgIuzvoWnfgXB2Fo0EPQzIqhV1MRcoSns6ngq1J7A4GEfLXo9cLO8N-Jxq6zYiisN.HGA-7nkjJM3H.RFo3inaGq8Yn3GvabJFNeS6UhZcd7dNSzieiQFSdIE4WObcka7OGdC5Fpup0.hQqa29vN2Abjgh0wCBDsIisUCyLOcgx3KrPfxU1phDpNcu.4pQVBX2xVLCCpD8lJwJ-r3iWFE8MoMU5y9kMHtfXwmLO4xWwfEJUOcfJrDB0T9WskKhNPtPa9Zrn40UW61BDgPK2QKdqc1FwKFQuYtXcx7EYQ.BDoKaiKAPg.K9J2zLsAMYiithTKtKjxaJh2ge0Qf.98gUeV3q65mnM0pQ0t8CwIYF2ReUsK8Yyn9m9K8f7lkDe.MVjBxIzcEtoUg0ZOdYO.MwSnvO8sBGkvx7HYaxkjmz4Gb4nWpFNwiOJNrpVj.qMzef86-S.pcv5NDo2VB7bhXb9kivLeCRnM5mFx0yxM6yeaeiReFyXc0wBfikXecwt54lIlfbFTJI3PhWF0QSlirAJLqEeCHy5uEXk06httc2uCQUHQFtCew04ybT71XBubaxmClLrxsW1yCiBtZSQBtUSv.eW9KBaWswTnYpu0QzrVttsnYs5T0WmM9Jab1jMCXJhV2vod9itzDexdAEPEc2nFv0B4bdyzFD6EX6OOiy4uppyxd7zQqYLrT6IOhuIsMhuIrk152sJMAOjmsZHG7N2G84R3pmiamonJc3swZilBe5JRXokU5lXQ6wCb6X8vJhfsZuUXyJQWP6e4fm2h-m34C0iOjn999lr-Pkl.qs404qtBRv.beSMtf5Xy8M8Z8t3dCg0aarZ8gnOqJGo.D5yk-HZ4cX15dHh28P3lyVoyOp1lstyNvxw-fr64vz03dX1yenrt8fXx4dXh3Xm30UhbkQq1NL67UXsfI7Qx5Vq5uAX7HQUsFuGByT6D0uuPAatGSuBpwBHTm41ySkG6H.OErEomrW10ptaGSGnaA3THoPw-vrVn9dnh7-9O736cPzaCFg5kBkOhNhpNl8oXWACL22hs5nuSGYZp3QJSphOuDpfKFy8kLkKtlrQLYHMqpJJ9XFzThCVVmHcCIzOtWXUcpFLnFfLYEsTH85uNIgDp43S29VwJIkldpf36n01w5KErAisTHME1avHKVYigVvy8KRw2IL1tFyYWmaqqKmO7qQy9n.bMPTGtLQ1X9ZKVbDJ3FcLkSZEDuOyA6mZfUMUm-ymTqoFItLtVvE7Sx3EdKeePfBc.sebWcwulC771p9EA2YrTHk2UdOKTE-vE1WrqOYEzagIcEIQmDwixHudqFDLlFAWuFzwqKkefJV-LNKUioPPIjFjMWGfZTo3NHS9aBg9CFtw9iKf7mxOUsnUTp8yNbAR2obIbqJhsdqIxmeLej5bjYV8-iZDVUBnbHnDqeaoKYdcTKb4tZxzT6QJ3LeNIJY2poEChNQMmxXg47GIdaaBkpBIbIOrzgsjwaDA-oVVjpHwnKEN2JxNWQblcbMNODLr2DXSR4FnUG3W9CJFaLALgPIhEGisiPBPZx8E.GxRqL9.OoCuxq7-iByiwQIZGSzUAg3Bj-ITktoQQ7mJH0X0yVAiS3i.YRl-gq5HstxM0vNIHnQT23F0Lo10yN0nrq-z73unw3t7U3G4aRMY2mb.GjUA09ahbyjdg.QmjytAGfIyaTYRe1Ax1DYhfVpzlDT8WOiezOGi6sWPpMwTkWEZK4KyFaSEm8SFPivsKKXyt0VPBVt2bS3YLUosB9BLOeOVQg3VRIyXlAAPL-NSawhwOoY7fZdhueIJ3Ak1BazUoHcDHhoWnxUHFu9EZk3lSZyhlCtdYmO5wFqKuRZPdROU6GsRrjshvmIocEvokqhNmqQQL5APZdD5nQAecXia5QJJ02UJerpmlVD58cdasOCHg4Nn4lUlwf-XOhthXUJ5Zbe8YXF6dX58vmcuahgXTGQ8TZYtcxJlnON1FqsFepzzMZ21NJ6yW32NThDhAk8jJ6vA0xZ0L0viMNh.TJmCYuqijfvBzcbpWOJtTX7mVNVbdvCHSNwhhOJYlth5W8V.BXgjM5kTu67ubbOMaaPdpVKUyHgxoyKndd9xJ8xgYSptddVQeIMKsN4R1HCfXuq8eCnUjGuAZAmFMGzYVILtr-zZAnuG4oLnF-Keu75hjUQ.fuG-7q9dSqgVosCb1oF6t01Z0oZDpVg8RZ95mhRfE3NsjnLdHdFhgM2anqJB.Uph32lcS457ni54secfWKtn7P3fFdm65qmqHad.rzLXaJe6.EOTVPkNHfVVV2LG9XbpUiF4srFF-0B31PW2rLzIbuonzaLfUTrlukB4zZXVjz6fmU.45WCTgR7Bly9lvltCo-0p5c9l9Snnqmphl0x76Vr5FXC8T5Y0usF8viH8vm6vPB9NL2OvTCfucvG3pJcTnjiMkOCvoQqHBlWejb4UxNdleYdDSaVUzWllaCOCW32a6hvjhkMWsVNztYpDJc6lf02h240aXmu7.Cxgj7kuj8t1xNpXmU3PJd--4eR8Jm.509uXe-7xDXHQ0rcqM28fE.X0fkMT2Sff4OnTYqv2eKhDhmXwnbwrH4ZBqMbac3DQJDmY-U1i1iXg6cumvgmgLA1qwpEGyPovEvYOpuHwXXQteHRhwwJkrFi5nzTG5QMtybESSpuNqboVM2llfgGhcXmtqjZLF821t1mXpvd7-teTZZji6WGnlm6KmUOaXmVXJJvy074uGfDveZhICLiPTgU2GzDcNz.lAHgXq2d4sHNpw3AL.gmdcDhAAZ2wN6jJoLP.GQkfmzcpiz83W82cJ.hX5rpbw48lT1N5hx-TnPMM.7.BQo..CTy1JxI.boVMuWp-wgzcp5bH-Jzk7E4jsb3duENaeUfvd5hKcqGCekLorabCMkB6syXhfFFMA.c7SKfjfv8YfOfvHlsNd7X397k0atWCQaej32u22.8F).

**Comment by jourdain** [comment]
I noticed some issue here:

```
    var mapper = vtkMapper.newInstance({
      // Orientation
      // orient: false,

      // Color
      // useLookupTableScalarRange: true,  // FIXME <----
      // lookupTable,                      // FIXME <----
      colorByArrayName: 'color',
      colorMode: vtk.Rendering.Core.vtkMapper.ColorMode.MAP_SCALARS,
      scalarMode: vtk.Rendering.Core.vtkMapper.ScalarMode.USE_POINT_FIELD_DATA,
      scalarVisibility: true,

      // Opactity
      // => not available yet

      // Scaling
      scaling: true,
      scaleArray: 'radius',
      scaleMode: vtk.Rendering.Core.vtkGlyph3DMapper.ScaleModes.SCALE_BY_MAGNITUDE,
    });
```

But by fixing that, I get the following error:

```
map.js:1819 Error: Coordinates are not valid
    at Function.s.transformCoordinatesArray (VM64 geo.min.js:39)
    at Function.s.transformCoordinates (VM64 geo.min.js:39)
    at vtkjs_pointFeature._build (about:blank:156)
    at vtkjs_pointFeature._update (about:blank:192)
    at _renderFrame (VM64 geo.min.js:39)
    at V (VM64 geo.min.js:83)
```

**Comment by manthey** [comment]
I've pushed a change that fixes setting the radius.  It still doesn't alter the color or opacity by point.  I've marked some TODO spots.

[Here is a tutorial editor link to this code, in case it is useful](https://opengeoscience.github.io/geojs/tutorials/editor/?src=rVnrb9s4Ev.uv2K2h1vLWVeRLTt-pFmsmzR7AZoH4nRxe0URMBJtcyuLhkQncVL.7zd8SZTtpMXd5oPDx2-Gw-G8SN2TDOZkAUcwpdzHlvdcA0h5TIfw5h.Yf9PEfkRTQbMhPMPjEN4Oev5BrwmrIYQtvx.AWkKeOJ8PoVNbNw5rSOZHGSWCfiQrmnl1ns.rOF67x9UiJhjNccHPSPWc8BQ59jp-EHQHnVbYhIQI5BP4vVa71w9xnZTMpTAX9AH-5NnXN01Y8MUSYUzS9jtBF2FKBsOt1er77U540O8MDLsQ-Xfb7bDTLth95DmM0ilNaL7BMez3O2FQ4djHHbcHvUG.beXDjff6rVZ4UDA8nrGITPkGs3avhcC2y2zQ9cODQT9o9w2z9sDvHQSd9kG52X.xZS54usmsNegOWh2XWa.rtw5wa62u3erAH3TbqJJBwexqxhIS02QxY2SDY6vbDZG-qr22H.Q6QdizhxGGfqeDOu61HJacpuxxi1srDA9669oXPGt12Cyd0YwJY16md6imMjplOVrVKdrJMqMGsjGqoQvOUlHFuUO42P7eXg324FgZHRBI0VhYmguSRhT4BO7F17.yCpGPeEnyW5SQPFctkjCSK-7bcAWgj4Kmcb4lgJpckIzM4Xlzzs8XNFoDyaYKlVEcTHON215mjaB9tWc1d7ux88kyjaSqwUN-DZCuWl.mFHKRsUjUD7HPJuD95IkZywsF2P1XuDU0OYCWSGlsG6XWkWxRMLkHlEH-fvsGz2s5XNlpRJJErdwETYYAuRWRkTSf8Gxuzq7oHxoAv.uLRtZIdMdOoUgVy8gwdmAzjWlGs9xoUP06FKNI8AzJsOlfKyxLp.4xRxntrIP-PVktZuHJOVks6MtUFZRDfUIEGWUZWRnKYz6f87QgK6YdkiuptDEVVQqJPMe4m.gOxKEaL9B56Jgvs4gaylOWCKkFPaj04KLUAWh1lmdTHsv8VlnJEagjU7YAOEikesruwkhSjuSKue3ntyxVDi65-KpTTtFHZ0p2yqnlIpauaid1V8mmfBlKb16wBU1YKj0WpHeAIdEZ5srMVrzD2nYpvtaYVauP1n5mvMNT9l1uTCNdPb6G9nMqbmZUkGua82Qpl.fCYAcIg.AuyL3Ov4XlVcyssvCzUd3-PlyiF6RCBV0zyNXIECYkyfFoSugxT3hWdjFYfOT863JxQ-4SOkarINk1wTQ4RC9d0qYCnZ79-.wDvHuLfyVlUpI1Yeffbso904ikIO9XyhcuVBKpq6F60wWcq8ID9WAUcGwH.fPR1e34ePRxdD0ujEiJv0kyLkb9T-MPt1eXZxc3t6dnHz6e3J6MbkZV4j9Yzu5YwsTKKMDMopk56l6gTyCkHDn6FUskAeSeYGZFjcCKCodAioCxw1kJe9UF5CBVykBFZCRmy7xemSu2VbWIsZ1Dr0dtfLh9.-ft-ej3i7ObTycfNIO1tT5NgbZ3li6WQsYXz.FnCHbjjnmaUuVHXmG.UyoulwInr3gmvEYTWoWFkzLWqsC621kUSi6ht-HpNTemcZWrjOO4WHkNCR7N76RZe3Y15fc2-CMk4liWPorrcoTEsZLCMzx17qqGlTMMUQyP5GkrophIth1HdJDTQVSHTZvitPzfFwx3o2vhyl42Ypi3S9z3S5bECg6TonSpiH2nELvkViVYE1go67T8D5JYE5MlfvpEM.4fZ2Q5vxIyH5j9xNJgGn5C06mYlTBkxNQqR6pmUDbsGdo9CBslUjLYZFfhc4oClwDL2AWhZ1RBuVglyh496zUOWoWQF.ETliQqnrgkHH0bXftVokuNccmWaA75Fc2u2CNNSsJEHXFD3aMafgXk7YTIW5PX0DlZyo-OY0WyRYVU8mnCiQjbrq6NGWkStfHvEpQRek5Wd1SFMDGjkLHpDFurBXVYau1-X4iajvJwJgAtdI5lD9DJhEXScUFwiDmW42UFiHZDIMdwiEGTKOYZQRmwSJyRFIp8tgfY0.NYvapGjkmuMqorm9zXrgCA.MFjKCwL8Sc4BAbvjFHL9i9H0JKuIBuhdRAwfoEExh49aaef2ReEGhWXJv-ZhV80Ekn8xx3T8Au0HMhqN6TtQJ5kMR1YnPVKqXLbxPlN8kMn2VybG5O1m31lDPv6.GoVK1dHh3tD7o7d79ox8sWqxnEoe2-Rh6Sr9QcmZpA1YdqEO3OsMjfJk.kcvEUteOhCfhMpY2kZz9lQ6h.TYIAE-LtuuInfEa1YdJdgjllqtIkQLhatp-J6mnZd24hehVGWF5JjzrOYpRiSc6-od5XbTqNc5r2dTqznNk66iUZWeseYz2m5oPSTmE1Wyvue3kbFqj7A2QQe5IWOZAIVp5SMWQekKcBTzThHSYGJKOZpXTgc58jlRqaLiC8xL6CjRzNZ4sXybojzlom7MORoD-rspEjTBKIl0iEPdaYxYLrGzJwxhCarwuPUXbOw059.rigLfjo6ekVfpQf-b36706cKP1qbI9-4BagSQ7ZznZJVTbTrxPZhJASJZjBhNInzl9ic6BQpqw4VFd0LX7V4Nw8ntubFzJwsaT50I.e6UdQTf8NCxsGdpSp55e9dzBawxVpu9iiWKkqSKMm2.Tz44pSkL1WEKn97SO9j5JH.pvrfnc5uN5cnl3hkj5p3.jovk9a9rVCoJdngaFDlRoxpq-Lrhs2pNG.pg4zGO-u4T-qGu1m7FdfgXUWnnnTLTmug0vOcusqsj1s810349WiXgA7g27fCkQxQr7aNfFe4dTFWuqGZ0jWorffXQPEaWmDkkb9eC.5YoVdkPV2hmHvVqb2B.N81mMs8dp51XnYR7GoXcWR0uaCzjIuLHnIquEpKw0MK4d2rvIXXyt3prLLVYo1aWWZrpjaiVZYt4M42qobqBMptQ3jVpk9oLjK-2jRq8-yz6z3m-zeljM75Pd2-xdn3JFcQa33ydqbHzWumHD6sSZB5c.a23zablddLaV3o7xf8oXiZBiZqG-.RXl3xwUhXV8Qy5G0.rcrXb-Ql7V6ZmrShzU8i5i4nLeaHcE2soIySMOBqKdb2m8qkeCFWfAyHQmYtqqy3tOfpTzCqX1y6ysOSYW7jcdh68uNQfr5Z-QlmSzO0skNEaFNSp6N4Kxc271baP4aOTcTKtp.tEpjooXeovyVhTVBeu16hwaphH3oN-CcEfq-LDAK.3a3wUPniFQ6f61ie1pt1nskKCRsrmiT8ARvTjNIU.99hQsN.LI3ZlGPjnvGECjVBoq.1L-ikh6rc0HuOM.IgLXF.r.aANPxBPRCiK.Gl8KoOIY9axZ4u4vWR-ItlPvPsh5ggsB9guj.44aVRs08E7jkXQq2b0A0CmWT39v8L).

**Comment by jourdain** [comment]
Is there still something for me to look at?

**Comment by manthey** [comment]
@aashish24 This works.  It has some mild eccentricities which I should document.  For instance, when zoomed out, points become annular:
image
Also, since in other renderers, points have strokes and/or fills, and here we only have fill values, I need to document that.  I should also add one more test.

**Comment by manthey** [comment]
@jourdain I hacked around how the lookup table returns color information.  I still have a color array, but the values of it don't seem to be used, and then I return a lookup table data array which has the packed rgba color values (which is where I end up supporting opacity).

I have two questions:

Is there a simple way to not need the extra color array?

Is there an example showing how to subclass something in vtkjs?  It seems like it would be betetr for me to subclass LookupTable instead of abusing it the way I did.

**Comment by jourdain** [comment]
For class extension: https://kitware.github.io/vtk-js/docs/develop_class.html

What do you colorBy if you don't have the color array? The LookupTable is meant to convert a field into an actual color. 

Since you seems to build the full RGBA for the full set of points, you should probably not use a lookup table and just use the raw data as an array in your pointset by setting "mapScalars=false".

**Comment by manthey** [comment]
@jourdain Thanks -- I've refactored this to be simpler.  I was misunderstanding the vtk.js documentation.

**Comment by manthey** [comment]
@aashish24 This is ready for review.

**Comment by aashish24** [comment]
> @aashish24 This is ready for review.

thanks. Do we still have the issue with "annular"? I believe that may be caused by clipping of spheres that are drawn by vtk.js.

**Comment by manthey** [comment]
> thanks. Do we still have the issue with "annular"? I believe that may be caused by clipping of spheres that are drawn by vtk.js.

Yes.  And, you are correct, it is the clipping.  We can set the clip bounds to a larger range -- but I think that we should defer that to a future PR where we add a more general method to get the extents needed and set the bounds based on the actual extents (so we don't degrade z-buffer precision needlessly).

**Comment by aashish24** [comment]
> Yes. And, you are correct, it is the clipping. We can set the clip bounds to a larger range -- but I think that we should defer that to a future PR where we add a more general method to get the extents needed and set the bounds based on the actual extents (so we don't degrade z-buffer precision needlessly).

sure sounds good. I guess this branch needs to be updated? Once that happens, I can approve it.

**Comment by manthey** [comment]
You can approve it while it updates -- the checks ensure that the merge to master will be valid.

**Pull request merged**
