### PR TITLE
[WIP] Choropleth feature

### PR DESCRIPTION
**Pull request by dcjohnston**
Early stage of the choropleth feature. To run the example, do everything you normally do to get the examples up and running (i.e. grunt serve) and then navigate to /examples/choropleth at localhost. There's some issue with the tooling whereby I have to run grunt manually to actually see my code update, even though grunt-serve does detect the changes and execute its tasks as expected, so I'll look into that sometime soon.

### CODE REVIEW

**Comment by jbeezley** [comment]
You can just push to a branch on this repo and issue a PR to master from that.

**Comment by aashish24** [comment]
Nice @dcjohnston. Can you do what @jbeezley suggested?

**Comment by dcjohnston** [comment]
Sure thing. I just tried pushing to new-classes branch and am getting permission denied. Not sure if it's something on my end but I wiped my local repo, recloned, and continue to get the same error, so I think there is a permissions issue.

**Comment by jbeezley** [comment]
I invited you to the OpenGeoscience organization.  You will need to accept that invite first.

**Comment by dcjohnston** [comment]
Apologies, missed that email. Okay, I've pushed to new-classes branch, should I close this issue and resubmit PR from there?

**Comment by jbeezley** [comment]
Yup, that will work.  Thanks.

**Pull request closed without merging**
