### PR TITLE
Preparing version 0.6.0-rc.1

### PR DESCRIPTION
**Pull request by jbeezley**
Bump version number and built sources

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley @manthey should we call it version 1.0 since this is a major change?

**Comment by aashish24** [comment]
Also, earlier, I created a milestone (https://github.com/OpenGeoscience/geojs/milestones/Version%201.0%20-%20Code%20name%20%22Jaguar%22) for this purpose.

**Comment by jbeezley** [comment]
No, 1.0 implies API stability, which we certainly don't have.

**Comment by aashish24** [comment]
> No, 1.0 implies API stability, which we certainly don't have.

What particular API you are referring to @jbeezley?  Or you are saying in general?

**Comment by aashish24** [comment]
@jbeezley we can discuss this in the new year. Sounds like it will require some good thinking and discussion.

**Comment by jbeezley** [comment]
Merged because this was already pushed to npm.  I was just waiting for the CI to pass.

**Pull request merged**
