### PR TITLE
Switch to earcut for triangulating polygons

### PR DESCRIPTION
**Pull request by jbeezley**
For the choropleth example, it is about 10x faster, 37 ms vs. 370 ms.

### CODE REVIEW

**Comment by jbeezley** [comment]
Closes #539

**Comment by aashish24** [comment]
this is great @jbeezley do you have performance improvement numbers? I am curious.

**Comment by aashish24** [comment]
:clap:

**Comment by aashish24** [comment]
@jbeezley LGTM, I didn't do timing test but I loaded a 44M geojson "watershed boundary areas" and it loaded fine.

**Comment by aashish24** [comment]
+2

**Pull request merged**
