### PR TITLE
Fix the map jumping at the end of some transitions.

### PR DESCRIPTION
**Pull request by manthey**
Sometimes, when zooming, the map would jump at the end of the transition.  This was caused by the zoom level reaching its final value, then a last animation frame firing, and asking to recenter the map when the center was already correct.

### CODE REVIEW

**Comment by manthey** [comment]
@aashish24 I think this was the problem you saw zooming with your laptop.

**Comment by aashish24** [comment]
@manthey is this what could cause the issue on some systems (like mine)? I will give it a try.

**Comment by aashish24** [comment]
@manthey seems to have fixed the issue! thanks. The code looks reasonable to me. How did you reproduce this bug on your system?

**Comment by manthey** [comment]
It happens much more rarely using a mouse wheel than you had with your track pad, but I noticed it on rare occasions, added some debug logging, and when it occurred, looked at what happened.

**Pull request merged**
