### PR TITLE
Add WMS server example

### PR DESCRIPTION
**Pull request by jamiesnape**
Live example at http://jsbin.com/vayude/edit

### CODE REVIEW

**Comment by aashish24** [comment]
@jamiesnape this is really nice. One issue I am having is that when you zoom out it seems to me that wms layer is no longer register correctly. Do you see it as well?

**Comment by jamiesnape** [comment]
@aashish24 Now you mention it, I see it. Seems to be tiles at the two smallest zoom levels where there is a big jump. Seems to be on the y-axis only.

**Comment by aashish24** [comment]
Right...I wonder why that would be. Some sort of offset / precision issue may be?

**Comment by jamiesnape** [comment]
The only possible source of loss of precision I can see would be the [```geo.mercator.tiley2lat```](https://github.com/OpenGeoscience/geojs/blob/master/src/core/mercator.js#L132) function.

This is the metadata for the layer from the WMS server, in case that helps explain it:

```xml
  <Layer queryable="1" opaque="0">
	<Name>topp:states</Name>
	<Title>USA Population</Title>
	<Abstract>2000 census data for United States.</Abstract>
	<KeywordList>
	  <Keyword>census</Keyword>
	  <Keyword>united</Keyword>
	  <Keyword>boundaries</Keyword>
	  <Keyword>state</Keyword>
	  <Keyword>states</Keyword>
	</KeywordList>
	<CRS>EPSG:4326</CRS>
	<CRS>CRS:84</CRS>
	<EX_GeographicBoundingBox>
	  <westBoundLongitude>-124.731422</westBoundLongitude>
	  <eastBoundLongitude>-66.969849</eastBoundLongitude>
	  <southBoundLatitude>24.955967</southBoundLatitude>
	  <northBoundLatitude>49.371735</northBoundLatitude>
	</EX_GeographicBoundingBox>
	<BoundingBox CRS="CRS:84" minx="-124.731422" miny="24.955967" maxx="-66.969849" maxy="49.371735"/>
	<BoundingBox CRS="EPSG:4326" minx="24.955967" miny="-124.73142200000001" maxx="49.371735" maxy="-66.969849"/>
	<Style>
	  <Name>population</Name>
	  <Title>Population in the United States</Title>
	  <Abstract>A sample filter that filters the United States into three
	categories of population, drawn in different colors</Abstract>
	  <LegendURL width="81" height="80">
		<Format>image/png</Format>
		<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://demo.boundlessgeo.com:80/geoserver/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=states"/>
	  </LegendURL>
	</Style>
	<Style>
	  <Name>population</Name>
	  <Title>Population in the United States</Title>
	  <Abstract>A sample filter that filters the United States into three
	categories of population, drawn in different colors</Abstract>
	  <LegendURL width="81" height="80">
		<Format>image/png</Format>
		<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://demo.boundlessgeo.com:80/geoserver/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=states&amp;style=population"/>
	  </LegendURL>
	</Style>
	<Style>
	  <Name>polygon</Name>
	  <Title/>
	  <Abstract/>
	  <LegendURL width="20" height="20">
		<Format>image/png</Format>
		<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://demo.boundlessgeo.com:80/geoserver/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=states&amp;style=polygon"/>
	  </LegendURL>
	</Style>
	<Style>
	  <Name>pophatch</Name>
	  <Title>Population in the United States</Title>
	  <Abstract>A sample filter that filters the United States into three
	categories of population, drawn in different colors</Abstract>
	  <LegendURL width="81" height="80">
		<Format>image/png</Format>
		<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://demo.boundlessgeo.com:80/geoserver/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=states&amp;style=pophatch"/>
	  </LegendURL>
	</Style>
  </Layer>
```

**Comment by aashish24** [comment]
@jamiesnape thanks for posting it. I think I know the problem. The WMS we are getting is in 4326 and map should convert it into 3057 but I think since you are using OSM layer which is not abstracted I think that conversion is not happening. So your layer is still drawn in 4326.

**Comment by aashish24** [comment]
So basically its a bug in GeoJS.

**Comment by aashish24** [comment]
I will create a new issue that describes this bug until then I am merging it.

**Pull request merged**
