### PR TITLE
Add the ability to change the tile url from the jquery plugin

### PR DESCRIPTION
**Pull request by jbeezley**
@ronichoudhury 

Adds `tileUrl` option to the jquery plugin.  You can also change the url dynamically by calling:
```
$('#map').geojsMap('tileUrl', 'http://otile1.mqcdn.com/tiles/1.0.0/osm/<zoom>/<x>/<y>.png');
```
http://jsbin.com/cuqasa/4/edit?js,output

I'll cut a release when merged.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Awesome, thanks!

**Comment by aashish24** [comment]
LGTM. Would it be tested? or do we need to add a test for it? I am assuming that @ronichoudhury will approve it.

**Comment by jbeezley** [comment]
Tests added.

**Comment by aashish24** [comment]
:+1:

**Comment by ronichoudhury** [comment]
I'm going to try this out while updating the map apps in the Tangelo examples.  Thanks!

**Comment by ronichoudhury** [comment]
This works great.  If/when there is a point release, I can shed the built version of this file in the Tangelo sources.

**Pull request merged**
