### PR TITLE
Build two bundles: full and lean

### PR DESCRIPTION
**Pull request by zachmullen**
@manthey @aashish24 this first commit represents the build configuration changes we discussed yesterday. If you approve of these changes, I'll go through and change the website and examples code.

### CODE REVIEW

**Comment by manthey** [comment]
@zachmullen This looks like a fine start.

@jbeezley Do you know what determines which files go to the CloudFlare CDN?

**Comment by jbeezley** [comment]
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/geojs/package.json

I don't remember exactly how it works, but any changes would have to be made as a PR to this file.

**Comment by zachmullen** [comment]
@manthey PTAL, I think this is ready for final review.

**Comment by aashish24** [comment]
@zachmullen this is super nice improvement..  👍

**Pull request merged**
