### PR TITLE
Allow slider widget to be repositioned

### PR DESCRIPTION
**Pull request by manthey**
It would be nicer if you could change the orientation and which ends had the + and - (or even if they appeared).

You can invoke the slide with the position option, which can contain offsets from the top, left, right, or bottom (or some combination thereof).  It can also take a width and height, which are honored, though height needs to be more than 3.5 times the width or stupid things will happen.

This addresses issue #618.

### CODE REVIEW

**Comment by manthey** [comment]
@dorukozturk Give this a try, passing something like `{position: {right: 20, top: 20}}`

**Comment by aashish24** [comment]
Looks reasonable to me but I will let @dorukozturk or @jbeezley approve it.

**Comment by manthey** [comment]
@jbeezley I added another change.  If you'd prefer, I could back it out and add it as a separate PR.

I also notice we don't test setting a widget position after its creation.  I'll add a test for that and for the recent change.

**Comment by jbeezley** [comment]
That's fine with me.   Thanks.

**Comment by manthey** [comment]
@jbeezley If this most recent change LGTY let me know (or just merge).

**Pull request merged**
