### PR TITLE
Added a function to change baseUrl.

### PR DESCRIPTION
**Pull request by manthey**
To change the tile set, call updateBaseUrl on the osm layer.  This moves all existing tiles to the zoom level of 'old' so that they will not be used, then updates the layer.

### CODE REVIEW

**Comment by jbeezley** [comment]
This is great.  I'll add a quick test as part of the osmLayer selenium test already in place.  Thanks @manthey.

**Comment by aashish24** [comment]
Nice. Quick question . Why keep the old tiles? Just wanted to get your thoughts.

**Comment by manthey** [comment]
Because I wasn't certain if removing them would have a negative effect: tiles that are not fully loaded will still call tileOnLoad.  At that point, if they aren't present, we would need logic in that routine to handle it.  By keeping the, the existing garbage collection will handle this.

**Comment by jbeezley** [comment]
Right. I think this is probably the path of least resistance here.

**Comment by aashish24** [comment]
If it is not too much work: I prefer we remove them. You can set the flag on the old ones because if on load gets called it may interfere with the current tiles. But j I havenot reviwed the branch very carefully

**Comment by jbeezley** [comment]
I'll look into it a bit later.

**Comment by manthey** [comment]
I'll refactor to remove the tiles later today or tomorrow.

**Comment by aashish24** [comment]
Sounds good, thanks. If it looks good then please merge and create new issue for it. I agree it's least resistance for now

**Comment by aashish24** [comment]
thanks @manthey. I am reviewing it now

**Comment by aashish24** [comment]
Looks good @manthey. I will just wait for the travis and then will merge it.

**Comment by manthey** [comment]
@aashish24 looks like Travis is stuck -- it passed, but isn't sending the results back to github.

**Comment by jbeezley** [comment]
Well, that's a new one.  I say merge it.

**Comment by aashish24** [comment]
yeah seems like it.. merging it fornow.

**Comment by jeffbaumes** [comment]
Absolutely. When in doubt, merge! :smile:

**Comment by aashish24** [comment]
@manthey one thought I had. Currently we list only one baseurl: m_baseUrl = "http://tile.openstreetmap.org/". Would it be possible for you to add list of good URL's (with one being the default). In that case, user can query list of possible URL's and use them appropriately. It will be helpful to provide this list for new users of GeoJS. The number of lines of code will be few. Thoughts?

**Comment by jbeezley** [comment]
I was planning to add an example with a widget for switching between tile servers.  I would probably do #279 and #281 along with this.

**Comment by aashish24** [comment]
@jbeezley that would be great.

**Pull request merged**
